/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {}
export type ExecuteMsg = {
  astro: {
    pair_address: string;
  };
} | {
  add_supported_pool: {
    pool_address: string;
    token_1: string;
    token_2: string;
  };
};
export type QueryMsg = {
  get_pair: {
    pool_address: string;
  };
} | {
  get_pool_addr: {
    token_1: string;
    token_2: string;
  };
};
export interface GetPairResponse {
  token_1: string;
  token_2: string;
}
export interface GetPoolAddrResponse {
  pool_addresses: string[];
}